name: main
on: [push, workflow_dispatch]
jobs:
  build:
    uses: TheSwissWizard/workflow-demo/.github/workflows/main.yml@main
    with:
      name: actions-demo
      java: 17
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
